import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import cookies from '../lib/cookies'
import SinergiAPi from '../lib/api'
import { useRouter } from 'next/router'

export default function Home() {

  let router = useRouter()
  const [username, setUsername] = useState()
  const [password, setPassword] = useState()
  const handleLogin = async () => {

    let userData = {
      username: username,
      password: password
    }

    let fetch = await SinergiAPi.User.Login(userData)
    let res = await fetch.json()

    if (fetch.status == 200) {
      // console.log(res)
      if (res.data.role != "Admin") {
        console.log('not authorized')
        // lw bikin sesuatu disini, pop up atau gimana, cuma role 1 yang bisa login sini
      } else {

        cookies.save("token", res.data.token, (1 / 1440) * 200)
        cookies.save("user", res.data.user, (1 / 1440) * 200)
        cookies.save("id", res.data.id, (1 / 1440) * 200)
        cookies.save("role", res.data.role, (1 / 1440) * 200)
        router.push('/penyuluhan');
      }
    } else {
      // tampilan kalau gagal
    }
  }

  useEffect(() => {
    let token = cookies.get("token")
    if (token !== undefined) {
      router.push("/penyuluhan")
    }
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Sinergi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.formContainer}>
        <div className={styles.greeting}>
          <h3>Selamat Datang di Monitoring Sinergi!</h3>
        </div>
        <div className="mb-3">
          <label htmlFor="exampleFormControlInput1" className="form-label">Username</label>
          <input type="text" className="form-control" id="exampleFormControlInput1" placeholder="username" onChange={(e) => setUsername(e.target.value)} />
        </div>
        <div className="form-group">
          <label htmlFor="exampleInputPassword1">Password</label>
          <input type="password" className="form-control" id="exampleInputPassword1" placeholder="Password" onChange={(e) => setPassword(e.target.value)} />
        </div>
      </div>
      <div className={styles.buttonContainer}>
        <button type="button" className="btn btn-success" onClick={() => handleLogin()}>Masuk</button>
        <button type="button" className="btn btn-link">Lupa Password?</button>
      </div>
    </div>
  )
}
