import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import cookies from '../lib/cookies'
import SinergiAPi from '../lib/api'
import { useRouter } from 'next/router'
import { InputText } from 'primereact/inputtext';
import { Password } from 'primereact/password';
import { Button } from 'primereact/button';

export default function Home() {

  let router = useRouter()
  const [username, setUsername] = useState()
  const [password, setPassword] = useState()
  const [loading1, setLoading1] = useState(false);

  const onLoadingClick1 = () => {
    setLoading1(true);

    setTimeout(() => {
        setLoading1(false);
    }, 10000);
}

  const handleLogin = async () => {

    let userData = {
      username: username,
      password: password
    }

    let fetch = await SinergiAPi.User.Login(userData)
    let res = await fetch.json()

    if (fetch.status == 200) {
      // console.log(res)
      if (res.data.role != "Admin") {
        console.log('not authorized')
        // lw bikin sesuatu disini, pop up atau gimana, cuma role 1 yang bisa login sini
      } else {

        cookies.save("token", res.data.token, (1 / 1440) * 200)
        cookies.save("user", res.data.user, (1 / 1440) * 200)
        cookies.save("id", res.data.id, (1 / 1440) * 200)
        cookies.save("role", res.data.role, (1 / 1440) * 200)
        router.push('/penyuluhan');
      }
    } else {
      // tampilan kalau gagal
    }
  }

  useEffect(() => {
    let token = cookies.get("token")
    if (token !== undefined) {
      router.push("/penyuluhan")
    }
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Sinergi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.formContainer}>
        <div className={styles.greeting}>
          <h3>Selamat Datang di Monitoring Sinergi!</h3>
        </div>
        <div className="col-12 md:col-4">
          <div className="p-inputgroup">
              <span className="p-inputgroup-addon">
                    <i className="pi pi-user"></i>
              </span>
              <InputText placeholder="Username" onChange={(e) => setUsername(e.target.value)} />
          </div>
        </div>
        <br/>
        <div className="col-12 md:col-4 mt-5">
          <div className="p-inputgroup">
              <span className="p-inputgroup-addon">
                    <i className="pi pi-lock-open"></i>
              </span>
              <Password  placeholder="Password" feedback={false} onChange={(e) => setPassword(e.target.value)}/>
          </div>
        </div>
        <br/>
      </div>
      <div className={styles.buttonContainer}>
      <Button label="Masuk" icon="pi pi-check" loading={loading1} iconPos="right" className="p-button-raised p-button-success mt-5" onClick={() => {onLoadingClick1(); handleLogin();}}/>
      </div>
    </div>
  )
}
